/**
 * Unified Security Graph — Seed Nodes
 *
 * Representative mock data covering every supported NodeType.
 * Modules can import these directly or use the graph utilities
 * to query/filter at runtime.
 */

import type { GraphNode } from "./types";

const now = "2026-03-11T00:00:00Z";
const ts = (daysAgo: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

export const SEED_NODES: GraphNode[] = [
  /* ── Assets ── */
  {
    id: "asset_finance_db_01",
    entity_type: "Asset",
    name: "finance-db-01",
    severity: "critical",
    risk_score: 92,
    status: "active",
    environment: "production",
    tags: ["database", "pci", "finance"],
    metadata: { ip: "10.0.12.5", os: "Ubuntu 22.04", owner: "finance-team" },
    timestamps: { created_at: ts(120), updated_at: ts(1) },
  },
  {
    id: "asset_web_01",
    entity_type: "Asset",
    name: "web-frontend-01",
    severity: "high",
    risk_score: 78,
    status: "active",
    environment: "production",
    tags: ["web", "public-facing", "react"],
    metadata: { ip: "10.0.1.20", os: "Alpine Linux", owner: "platform-team" },
    timestamps: { created_at: ts(200), updated_at: ts(3) },
  },
  {
    id: "asset_k8s_node_01",
    entity_type: "Asset",
    name: "k8s-node-prod-01",
    severity: "high",
    risk_score: 74,
    status: "active",
    environment: "production",
    tags: ["kubernetes", "container", "compute"],
    metadata: { cluster: "prod-east-1", nodePool: "general" },
    timestamps: { created_at: ts(90), updated_at: ts(2) },
  },
  {
    id: "asset_cicd_runner",
    entity_type: "Asset",
    name: "cicd-runner-03",
    severity: "medium",
    risk_score: 55,
    status: "active",
    environment: "shared",
    tags: ["ci", "build", "devops"],
    metadata: { provider: "GitHub Actions", self_hosted: true },
    timestamps: { created_at: ts(60), updated_at: ts(5) },
  },

  /* ── Vulnerabilities ── */
  {
    id: "vuln_cve_2023_4211",
    entity_type: "Vulnerability",
    name: "CVE-2023-4211",
    severity: "critical",
    risk_score: 95,
    status: "open",
    environment: "production",
    tags: ["rce", "gpu", "arm"],
    metadata: { cvss: 9.8, vector: "NETWORK", exploitAvailable: true },
    timestamps: { created_at: ts(30), updated_at: ts(1) },
  },
  {
    id: "vuln_cve_2024_1001",
    entity_type: "Vulnerability",
    name: "CVE-2024-1001",
    severity: "high",
    risk_score: 82,
    status: "open",
    environment: "production",
    tags: ["sqli", "database"],
    metadata: { cvss: 8.6, vector: "NETWORK", exploitAvailable: false },
    timestamps: { created_at: ts(14), updated_at: ts(2) },
  },
  {
    id: "vuln_cve_2024_3055",
    entity_type: "Vulnerability",
    name: "CVE-2024-3055",
    severity: "medium",
    risk_score: 58,
    status: "in_progress",
    environment: "staging",
    tags: ["xss", "frontend"],
    metadata: { cvss: 6.1, vector: "NETWORK", exploitAvailable: false },
    timestamps: { created_at: ts(7), updated_at: ts(1) },
  },

  /* ── Misconfigurations ── */
  {
    id: "misconfig_s3_public",
    entity_type: "Misconfiguration",
    name: "S3 Bucket Public Access",
    severity: "critical",
    risk_score: 90,
    status: "open",
    environment: "production",
    tags: ["s3", "aws", "public-access"],
    metadata: { bucket: "corp-reports-2026", region: "us-east-1" },
    timestamps: { created_at: ts(5), updated_at: ts(1) },
  },
  {
    id: "misconfig_ssh_root",
    entity_type: "Misconfiguration",
    name: "SSH Root Login Enabled",
    severity: "high",
    risk_score: 76,
    status: "open",
    environment: "production",
    tags: ["ssh", "linux", "hardening"],
    metadata: { host: "10.0.12.5" },
    timestamps: { created_at: ts(20), updated_at: ts(3) },
  },

  /* ── Attack Paths ── */
  {
    id: "ap_lateral_finance",
    entity_type: "AttackPath",
    name: "Lateral Movement to Finance DB",
    severity: "critical",
    risk_score: 94,
    status: "active",
    environment: "production",
    tags: ["lateral-movement", "privilege-escalation"],
    metadata: { steps: 4, entryPoint: "asset_web_01", target: "asset_finance_db_01" },
    timestamps: { created_at: ts(10), updated_at: ts(1) },
  },
  {
    id: "ap_cloud_escape",
    entity_type: "AttackPath",
    name: "Container Escape to Cloud Control Plane",
    severity: "high",
    risk_score: 81,
    status: "active",
    environment: "production",
    tags: ["container-escape", "cloud"],
    metadata: { steps: 3, entryPoint: "asset_k8s_node_01" },
    timestamps: { created_at: ts(8), updated_at: ts(2) },
  },

  /* ── Risks ── */
  {
    id: "risk_data_exfil",
    entity_type: "Risk",
    name: "Data Exfiltration — Finance",
    severity: "critical",
    risk_score: 96,
    status: "active",
    environment: "production",
    tags: ["data-exfiltration", "pci"],
    metadata: { impactArea: "financial-data", likelihood: "high" },
    timestamps: { created_at: ts(10), updated_at: ts(1) },
  },
  {
    id: "risk_supply_chain",
    entity_type: "Risk",
    name: "Supply Chain Compromise",
    severity: "high",
    risk_score: 79,
    status: "active",
    environment: "shared",
    tags: ["supply-chain", "ci-cd"],
    metadata: { impactArea: "build-pipeline", likelihood: "medium" },
    timestamps: { created_at: ts(15), updated_at: ts(4) },
  },

  /* ── Cases ── */
  {
    id: "case_ir_001",
    entity_type: "Case",
    name: "IR-2026-001: Suspicious DB Access",
    severity: "critical",
    risk_score: 88,
    status: "in_progress",
    environment: "production",
    tags: ["incident", "database", "unauthorized-access"],
    metadata: { assignee: "user_analyst_01", priority: "P1" },
    timestamps: { created_at: ts(3), updated_at: ts(0) },
  },
  {
    id: "case_ir_002",
    entity_type: "Case",
    name: "IR-2026-002: Phishing Campaign",
    severity: "high",
    risk_score: 72,
    status: "open",
    environment: "external",
    tags: ["phishing", "email", "social-engineering"],
    metadata: { assignee: "user_analyst_02", priority: "P2" },
    timestamps: { created_at: ts(2), updated_at: ts(0) },
  },

  /* ── Workflows ── */
  {
    id: "wf_isolate_host",
    entity_type: "Workflow",
    name: "Isolate Compromised Host",
    severity: "high",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["response", "containment", "automated"],
    metadata: { steps: 5, trigger: "manual", avgRuntime: "12s" },
    timestamps: { created_at: ts(60), updated_at: ts(10) },
  },
  {
    id: "wf_patch_vuln",
    entity_type: "Workflow",
    name: "Auto-Patch Vulnerability",
    severity: "medium",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["patching", "remediation", "automated"],
    metadata: { steps: 8, trigger: "scheduled", avgRuntime: "45s" },
    timestamps: { created_at: ts(45), updated_at: ts(5) },
  },

  /* ── Workflow Runs ── */
  {
    id: "wfr_isolate_001",
    entity_type: "WorkflowRun",
    name: "Isolate Host — Run #127",
    severity: "info",
    risk_score: 0,
    status: "resolved",
    environment: "production",
    tags: ["success"],
    metadata: { workflow_id: "wf_isolate_host", duration_ms: 11200, exit_code: 0 },
    timestamps: { created_at: ts(1), updated_at: ts(1) },
  },
  {
    id: "wfr_patch_001",
    entity_type: "WorkflowRun",
    name: "Auto-Patch — Run #84",
    severity: "medium",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["running"],
    metadata: { workflow_id: "wf_patch_vuln", duration_ms: null, exit_code: null },
    timestamps: { created_at: ts(0), updated_at: ts(0) },
  },

  /* ── Approvals ── */
  {
    id: "appr_isolate_001",
    entity_type: "Approval",
    name: "Approve Host Isolation — finance-db-01",
    severity: "critical",
    risk_score: 0,
    status: "pending",
    environment: "production",
    tags: ["containment", "requires-approval"],
    metadata: { workflow_run_id: "wfr_isolate_001", requester: "agent_sentinel" },
    timestamps: { created_at: ts(1), updated_at: ts(0) },
  },

  /* ── Integrations ── */
  {
    id: "integ_crowdstrike",
    entity_type: "Integration",
    name: "CrowdStrike Falcon",
    severity: "info",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["edr", "endpoint"],
    metadata: { vendor: "CrowdStrike", apiVersion: "v2", healthCheck: "ok" },
    timestamps: { created_at: ts(180), updated_at: ts(1) },
  },
  {
    id: "integ_splunk",
    entity_type: "Integration",
    name: "Splunk SIEM",
    severity: "info",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["siem", "logging"],
    metadata: { vendor: "Splunk", apiVersion: "v3", healthCheck: "ok" },
    timestamps: { created_at: ts(180), updated_at: ts(2) },
  },

  /* ── Users ── */
  {
    id: "user_analyst_01",
    entity_type: "User",
    name: "Sarah Chen",
    severity: "info",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["analyst", "soc-l2"],
    metadata: { role: "Senior Analyst", email: "s.chen@example.com" },
    timestamps: { created_at: ts(365), updated_at: ts(0) },
  },
  {
    id: "user_analyst_02",
    entity_type: "User",
    name: "Marcus Johnson",
    severity: "info",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["analyst", "soc-l1"],
    metadata: { role: "Analyst", email: "m.johnson@example.com" },
    timestamps: { created_at: ts(200), updated_at: ts(0) },
  },

  /* ── Identities ── */
  {
    id: "ident_svc_deploy",
    entity_type: "Identity",
    name: "svc-deploy-prod",
    severity: "high",
    risk_score: 68,
    status: "active",
    environment: "production",
    tags: ["service-account", "deploy", "over-privileged"],
    metadata: { type: "service_account", permissions: 42, lastUsed: ts(0) },
    timestamps: { created_at: ts(90), updated_at: ts(0) },
  },
  {
    id: "ident_admin_legacy",
    entity_type: "Identity",
    name: "admin-legacy-root",
    severity: "critical",
    risk_score: 88,
    status: "active",
    environment: "production",
    tags: ["root", "legacy", "over-privileged"],
    metadata: { type: "user_account", permissions: 128, lastUsed: ts(30) },
    timestamps: { created_at: ts(500), updated_at: ts(30) },
  },

  /* ── Applications ── */
  {
    id: "app_payment_api",
    entity_type: "Application",
    name: "Payment API Service",
    severity: "critical",
    risk_score: 85,
    status: "active",
    environment: "production",
    tags: ["api", "payment", "pci"],
    metadata: { language: "Java", framework: "Spring Boot", repo: "payments-api" },
    timestamps: { created_at: ts(300), updated_at: ts(2) },
  },

  /* ── Policies ── */
  {
    id: "policy_mfa_required",
    entity_type: "Policy",
    name: "MFA Required for All Users",
    severity: "high",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["iam", "mfa", "authentication"],
    metadata: { enforcementLevel: "mandatory", exceptions: 3 },
    timestamps: { created_at: ts(180), updated_at: ts(15) },
  },
  {
    id: "policy_no_public_s3",
    entity_type: "Policy",
    name: "No Public S3 Buckets",
    severity: "critical",
    risk_score: 0,
    status: "active",
    environment: "production",
    tags: ["cloud", "s3", "data-protection"],
    metadata: { enforcementLevel: "mandatory", violations: 1 },
    timestamps: { created_at: ts(120), updated_at: ts(5) },
  },

  /* ── Compliance Controls ── */
  {
    id: "cc_pci_321",
    entity_type: "ComplianceControl",
    name: "PCI-DSS 3.2.1 — Encryption at Rest",
    severity: "critical",
    risk_score: 0,
    status: "compliant",
    environment: "production",
    tags: ["pci", "encryption", "data-at-rest"],
    metadata: { framework: "PCI-DSS", control: "3.2.1", lastAudit: ts(7) },
    timestamps: { created_at: ts(365), updated_at: ts(7) },
  },
  {
    id: "cc_soc2_cc7",
    entity_type: "ComplianceControl",
    name: "SOC2 CC7.2 — Incident Response",
    severity: "high",
    risk_score: 0,
    status: "non_compliant",
    environment: "production",
    tags: ["soc2", "incident-response"],
    metadata: { framework: "SOC2", control: "CC7.2", lastAudit: ts(14) },
    timestamps: { created_at: ts(365), updated_at: ts(14) },
  },
];
